### PR TITLE
chore: Build documentation and deploy to GitHub Pages

### PR DESCRIPTION
**Pull request by luator**
Rebuild is done for push to master, pull requests that have a change inside docs/ and workflow_dispatch.
Publishing to Pages only happens for push on master or workflow_dispatch if the corresponding option is set.

### CODE REVIEW

**Comment by luator** [comment]
Unfortunately this is a bit annoying to properly test as deployment is only happening when pushing to master.  Se we cannot see how the build documentation looks like before merging.

**Review by mseitzer — APPROVED** [review]
LGTM!

**Comment by mseitzer** [comment]
Can the built documentation be used as an ouput artifact of the job? Then it would be possible to manually download and inspect.

**Comment by luator** [comment]
> Can the built documentation be used as an ouput artifact of the job? Then it would be possible to manually download and inspect.

I think in theory yes, but it seems it only creates an artifact when actually publishing.

**Pull request merged**
